name: solid-design-principles
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9

  # Core Jupyter dependencies
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - ipykernel>=6.0.0

  # Data science stack
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0

  # Testing
  - pytest>=6.2.0

  # Optional: Enhanced notebook experience
  - jupyter-contrib-nbextensions>=0.7.0
  - jupyter-nbextensions-configurator>=0.4.0

  # Optional: Code quality tools
  - black>=21.0.0
  - flake8>=3.9.0
  - mypy>=0.910

  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
    # Add any pip-only packages here if needed
    - jupyter-contrib-nbextensions>=0.7.0
